### ISSUE TITLE
more robust date parsing

### ISSUE THREAD

**Issue by AXGKl** [telecomshy/imap-easybox#1]
Hi, thanks for this, super easy in deed!

In my inbox I got a few errors with the date parser:

Logged them via `            print('Err: unreadable date: ', mail.headers['date'])`:

```
Err: unreadable date:  3 Nov 2023 07:40:52 -0400
Err: unreadable date:  Thu, 2 Nov 2023 09:37:33 GMT
Err: unreadable date:  Mon, 30 Oct 2023 13:09:27 GMT
Err: unreadable date:  Sat, 07 Oct 2023 18:58:21 GMT
Err: unreadable date:  28 Sep 2023 04:56:55 -0400
```

imaplib also fails parsing them.

Not sure if should monkeypatch your email.Mail.date property or you want to deal with that stuff (?)

**Comment by axgkl** [comment]
ty for merging.
